import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#9c6644]'>
        <div className="max-w-5xl px-8  mx-auto flex flex-col items-center">
        <NavBar/>
        {children}
        </div>
        
        </body>
    </html>
  );
}
